language: node_js
node_js:
  - '7'
  - '8'
  - '10'

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: '7'
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        on:
          tags: true
        edge: true
    - stage: GitHub Release
      if: tag IS present
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: {}
        cleanup: true
        release_notes_file: CHANGELOG.md
        name: $TRAVIS_TAG
        on:
          tags: true
        edge: true
